CREATE TABLE rss (
  id INTEGER NOT NULL PRIMARY KEY,
  url TEXT NOT NULL UNIQUE,
  feed_id INTEGER,
  read BOOLEAN,
  pub_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  content TEXT UNIQUE,
  title TEXT UNIQUE
)
